networks:
  1panel-network:
    external: true
services:
  ztnet:
    container_name: ztnet
    env_file:
    - ./envs/global.env
    - .env
    environment:
    - TZ=Asia/Shanghai
    - NEXTAUTH_URL_INTERNAL=http://ztnet:3000
    image: sinamics/ztnet:0.8.3
    labels:
      createdBy: Apps
    networks:
    - 1panel-network
    ports:
    - ${PANEL_APP_PORT_HTTP}:3000
    restart: always
